### ISSUE TITLE
update-initramfs destroyed boot.img

### ISSUE THREAD

**Issue by wdehoog** [ubports/ubuntu-touch-for-oneplus-one#14]
Using adb networking while trying apt-get upgrade I got these errors:

Processing triggers for initramfs-tools (0.103ubuntu13) ...
update-initramfs: Generating /boot/initrd.img-touch
dpkg: warning: version 'touch' has bad syntax: version number does not start with digit
grep: /boot/config-touch: No such file or directory
WARNING: missing /lib/modules/touch
Device driver support needs thus be built-in linux image!
depmod: FATAL: touch: not absolute path.
depmod: ERROR: could not open directory /tmp/mkinitramfs_JZKI7m/lib/modules/3.4.0-cyanogenmod-g92e6a17: No such file or directory
depmod: FATAL: could not search modules: No such file or directory
reading ramdisk from /boot/initrd.img-touch
Writing Boot Image /dev/disk/by-partlabel/boot

and then booting failed. Restoring twrp backup of boot.img made the device boot again.

**Comment by mariogrip** [comment]
I'm sorry for not responding to this issue, i did't see it before now. still need help with adb networking?

**Comment by wdehoog** [comment]
The adb networking worked. The question was about the problem with dpkg upgrade. I don't think it is of any importance anymore and I'll close the issue.
