### ISSUE TITLE
Stuck at transfering rootfs tarball

### ISSUE THREAD

**Issue by SmileDrug** [ubports/ubuntu-touch-for-oneplus-one#17]
smiledrug@smiledrug-Inspiron-3521:~/LocalDickF/one+one/images$ sudo ./OnePlusOne-rootstock-installer wily-preinstalled-touch-armhf.tar.gz system.img
transfering rootfs tarball ... smiledrug@smiledrug-Inspiron-3521:~/LocalDickF/one+one/images$

**Comment by wdehoog** [comment]
The install script assumes there exists a directory on your phone called /recovery. There it copies the tarball into. On my phone it did not exist and I got the same output as you. I modified the script to use /sdcard instead (which exist on my phone). Now copying works.

Also check if you need to modify the script for the correct system.img see https://forums.oneplus.net/threads/wip-ubuntu-touch-for-oneplus-one.266170/page-47#post-10893871.

**Comment by mariogrip** [comment]
have you checked if you're connected to the device? 

adb devices

**Comment by vinay10949** [comment]
./OnePlusOne-rootstock-installer wily-preinstalled-touch-armhf.tar.gz UbuntuTouch-system.img
transfering rootfs tarball ... 

After then i tweak the installer file
Replace below lines in "OnePlusOne-rootstock-installer"
Code:
convert_android_img
ANDROID_DIR="/cache/system/var/lib/lxc/android/"
adb push $WORKDIR/system.img $ANDROID_DIR >/dev/null 2>&1
with these
Code:
#convert_android_img
ANDROID_DIR="/cache/system/var/lib/lxc/android/"
adb push system.img $ANDROID_DIR >/dev/null 2>&1


Still dint work
