### ISSUE TITLE
build does not start because lunch fails

### ISSUE THREAD

**Issue by wdehoog** [ubports/ubuntu-touch-for-oneplus-one#18]
As the title says building fails. The errors are like the log from the failed builds on the build server (http://ci.mariogrip.com).

It seems that various environment variables that are supposed to be created like PRODUCT_OUT and TARGET_OUT are not defined. They seem to be created when ./build/core/envsetup.mk is used but I cannot find how or where this is done.

**Comment by mariogrip** [comment]
Thanks for the information, i will take a look at it.

**Comment by wdehoog** [comment]
Thanks for looking into this. Tried to follow the install instructions from fresh again. After 'lunch aosp_bacon-userdebug' I get warnings like:

ln: failed to create symbolic link â/etc/firmware/wcd9320/wcd9320_anc.binâ: No such file or directory
ln: failed to create symbolic link â/etc/firmware/wcd9320/wcd9320_mbhc.binâ: No such file or directory

When running make it stops after quit some time with:

Import includes file: /home/neil/phablet/out/target/product/bacon/obj/SHARED_LIBRARIES/copybit.msm8974_intermediates/import_includes
target thumb C++: copybit.msm8974 <= hardware/qcom/display/msm8974/libcopybit/copybit_c2d.cpp
hardware/qcom/display/msm8974/libcopybit/copybit_c2d.cpp:34:28: fatal error: linux/msm_kgsl.h: No such file or directory
compilation terminated.
build/core/binary.mk:432: recipe for target '/home/neil/phablet/out/target/product/bacon/obj/SHARED_LIBRARIES/copybit.msm8974_intermediates/copybit_c2d.o' failed
make: *** [/home/neil/phablet/out/target/product/bacon/obj/SHARED_LIBRARIES/copybit.msm8974_intermediates/copybit_c2d.o] Error 1

**Comment by DomThePorcupine** [comment]
Did you ever fix the ln errors?

**Comment by mariogrip** [comment]
Fixed in 5.1
