### ISSUE TITLE
SIM Card not detected

### ISSUE THREAD

**Issue by anidotnet** [ubports/ubuntu-touch-for-oneplus-one#22]
I just installed ubuntu touch on my OPO using MultiROMMgr-UT.apk. After installing I am able to boot into ubuntu. But it is not able to detect the SIM card (vodafone-india) and is not able to browse internal SD card.
Is that a known bug? Or do I need to do something to get it resolve?

**Comment by mariogrip** [comment]
We are working on getting cellular network working (SIM card).

The Ubuntu file system is completely different from android. There is no "internal SD card", instead it works like a computer, your files is saved in /home/phablet. if you want access the android files you need to do some terminal magic 

```
adb shell
```

In adb shell:

```
su - phablet
cd ~
sudo mkdir android 
sudo mount --bind /userdata/media/0 ~/android
sudo chmod 775 android
sudo chown phablet:phablet android
```

**Comment by aalasolutions-zz** [comment]
What is the status now? I just purchased nexus 4 for Ubuntu and my sim is not working. I am on 15.04 20151118 build.

**Comment by anidotnet** [comment]
What is the status now? Has this project been abandoned?

**Comment by mariogrip** [comment]
Sorry for late reply, I'll take a look at it as soon as I can.

**Comment by mariogrip** [comment]
Is it on your nexus that sim is not working?

@anidotnet
I'm still working on it, but I'm currently working on a new ubuntu android
tree based on cm12 (lollipop) so that's why it takes time.

**Comment by aalasolutions-zz** [comment]
@mariogrip yes, i figured that out that my sim connectors are damaged, sent it to hardware guy and now having ghost touches.. so didnt used that phone for even 2 days.. :(

**Comment by ValeWalker27** [comment]
I still am facing the same issue. I want to use my OPO running Ubuntu touch, as a spare but SIM card is not recognised. I have tried SIM cards from multiple mobile service providers. Would really like to know if there is any fix identified.
