### ISSUE TITLE
MultiRom Recovery Broken

### ISSUE THREAD

**Issue by Bricksey** [ubports/ubuntu-touch-for-oneplus-one#23]
When trying to use (and boot into) the custom recovery to install Ubuntu touch, it will reboot, show the bootlogo for longer than it normally would, then reboot again, back into the multirom selection screen. Then, since it hasn't been able to install Ubuntu touch in the recovery,it throws an error when attempting to run it.

**Comment by mariogrip** [comment]
Are you using the Ubports TWRP?

What ubuntu touch version are you trying to install?

**Comment by Bricksey** [comment]
I downloaded the modified version of multirom and installed the modified
recovery through there and I am trying to install stable version 7. (I
think the fault is mostly in the recovery as I have got it to install with
the recovery given by the official multirom app, but it doesn't start. The
modified recovery won't even start)

**Comment by Turakar** [comment]
I have the same problem. I tried to install the recovery, but booting to recovery does not work. After the boot logo vanishes and the twrp logo should come up, the phone reboots.

**Comment by UniversalSuperBox** [comment]
Cleaning up old issues
