### ISSUE TITLE
Recovery not booting

### ISSUE THREAD

**Issue by xxxLagg100xxx** [ubports/ubuntu-touch-for-oneplus-one#24]
Hello, i want to install ubuntu touch with multirom. I downloaded the modified apk and installed Multirom v32j and Recovery (5.0.x kernel is already installed). Recovery installs successfully and multirom install needs recovery. Then the device tries to reboot recovery but the oneplus logo stays longer than normally and then multirom os selection comes up. Please help!

**Comment by Turakar** [comment]
Duplicate #23

**Comment by makayama** [comment]
you can solve this problem by install stable version channel 7 than after boot startup you can update by access to setting you need to enable your wifi network to connect to internet to allow dowbload the update the move you to channel 8 stable version that all .

**Comment by tax3178** [comment]
Hey there,
as I can do this without MultiROM?
now I have 9
thank you

**Comment by UniversalSuperBox** [comment]
Cleaning up old issues
