### ISSUE TITLE
video decoder support ,camera , sim and gps

### ISSUE THREAD

**Issue by makayama** [ubports/ubuntu-touch-for-oneplus-one#25]
the mp3 sound work fine it was impressive that sound integration very good 
but the problem that there no video player and codec supported such as mp4 , avi ,wmv , mkv, quicktime ,etc to work ,need solve problem quickly please .

also need camera to work and GSM that helping to share location like google maps web apps unofficial and   sim to makes  call and receive message .

**Comment by mariogrip** [comment]
I'm currently working on a new ubuntu android tree based on cm12 (lollipop)
so I'll fix this in that version.

**Comment by UniversalSuperBox** [comment]
Cleaning up old issues
