### ISSUE TITLE
What is holding back Bluetooth?

### ISSUE THREAD

**Issue by ryanleesipes** [ubports/ubuntu-touch-for-oneplus-one#27]
I'm interested in what is holding back the bluetooth implementation? Is it something that is simply really hard to implement or is there an actual hard limitation that prevents it altogether?

**Comment by mariogrip** [comment]
I haven't really looked in to that issue yet. After I got cell "working" have been working on getting the android hal to 5.1, which I'm currently having some graphics issues.

**Comment by ryanleesipes** [comment]
@mariogrip gotcha, thanks for the response. Really excited to use this as my daily driver - but bluetooth and headphones are two big things for me.
