### ISSUE TITLE
maby the MultiRom Recovery can enable Ubuntu touch for bacon

### ISSUE THREAD

**Issue by wangyou** [ubports/ubuntu-touch-for-oneplus-one#28]
you can see this committ https://github.com/Tasssadar/Team-Win-Recovery-Project/commit/d0d38beabe1e7daf13f7771537c7aa6265e70da6
so, can we enjoy the Ubuntu Touch ????

**Comment by UniversalSuperBox** [comment]
Cleaning up old issues
