### ISSUE TITLE
my oneplus one cant boot the ubuntu touch

### ISSUE THREAD

**Issue by wangyou** [ubports/ubuntu-touch-for-oneplus-one#29]
i used multirom
log：
[Uploading multirom_log.txt…]()

**Comment by joelheaps** [comment]
Your link doesn't work.  I opened a new issue (with more info), possibly same as yours, but you didn't really provide enough info to know.  You can monitor both to see if we can get an answer.

**Comment by UniversalSuperBox** [comment]
Cleaning up old issues
