### ISSUE TITLE
Incoming or Outgoing Calls not working

### ISSUE THREAD

**Issue by shaouraav** [ubports/ubuntu-touch-for-oneplus-one#30]

**Comment by jodanlime** [comment]
I am also having this problem with ubuntu touch on my one plus one. I have installed the latest dev build with multirom. I have ATT, and when I go to "Cellular Settings" It claims that I am in a 4G zone but when I turn WiFi off I cannot access any data or make any calls/texts. When I try to access the APN settings I cannot access the menu and the settings app freezes until I close it.

**Comment by govinda9** [comment]
Also having problem with receiving calls on the phone (Multirom with ubuntu stable Version)

**Comment by UniversalSuperBox** [comment]
Cleaning up old issues
