### ISSUE TITLE
What is Canonical demoeing om 2016 MWC? Is canonical demoing fully-fixed version? with camera and Bluetooth working?

### ISSUE THREAD

**Issue by linuxd3v** [ubports/ubuntu-touch-for-oneplus-one#31]
What is Canonical [demoing om 2016 MWC](https://insights.ubuntu.com/2016/02/19/community-collaborates-on-new-convergent-ubuntu-phones/)?    

Does their version actually has camera and Bluetooth fixed? 
Or are they just demoing what's  available?

**Comment by mariogrip** [comment]
They are demoing the stable version from ubports, so no camera and bt
