### ISSUE TITLE
Download Link Broken <wily-preinstalled-touch-armhf.tar.gz>

### ISSUE THREAD

**Issue by mitchbw** [ubports/ubuntu-touch-for-oneplus-one#33]
The Link found on [this page](https://wiki.ubports.com/w/OnePlus_One#Alternative_to_MultiRom_using_rootstock_installer_.28OLD_METHOD.29) the last out of three files (UbuntuTouch-opo-installer.zip, UbuntuTouch-20150413-bacon-DEV.zip and **wily-preinstalled-touch-armhf.tar.gz**) required for manual loading of Ubuntu Touch (through TWRP) is sadly broken and produces a "404 Not Found"

This is the Link in question: [http://cdimage.ubuntu.com/ubuntu-touch/daily-preinstalled/current/wily-preinstalled-touch-armhf.tar.gz](http://cdimage.ubuntu.com/ubuntu-touch/daily-preinstalled/current/wily-preinstalled-touch-armhf.tar.gz)

As the shorter URL of [http://cdimage.ubuntu.com/ubuntu-touch/daily-preinstalled/](http://cdimage.ubuntu.com/ubuntu-touch/daily-preinstalled/) brings a valid link it does not seam as though there is a typo (although I could happily be wrong about that).

I have had a lengthy search of the interwebs and I cannot get my hands on this required file.

Is there a way around this?
Is the required file/folder located within another zip or img to be extracted?

**Comment by mariogrip** [comment]
Use this one: http://cdimage.ubuntu.com/ubuntu-touch/vivid/daily-preinstalled/current/vivid-preinstalled-touch-armhf.tar.gz

i will fix the link at the wiki

**Comment by eedam** [comment]
http://mirrors.ubuntu.webair.com/ubuntu-cdimage/ubuntu-touch/daily-preinstalled/current/
here is it dude good luck
