### ISSUE TITLE
Vertical Lines in the middle of OnePlusOne

### ISSUE THREAD

**Issue by d3cxxxx** [ubports/ubuntu-touch-for-oneplus-one#34]
I see a couple of vertical lines (refreshing at a high rate) all the way from boot to running the OS. 
Attached a snapshot showing the same. 
Let me know how I can help debug the issue (if you need some kind of logs)
![2016-03-02](https://cloud.githubusercontent.com/assets/8533272/13468020/c4b4e344-e06e-11e5-8631-e62c1fc1dff6.png)

**Comment by mariogrip** [comment]
Could you send me some logs? 

enable developer mode:

syslog:
adb pull /var/log/syslog

logcat:
adb shell /system/bin/logcat

**Comment by d3cxxxx** [comment]
Here you go.

[logcat.txt](https://github.com/ubports/ubuntu-touch-for-oneplus-one/files/162213/logcat.txt)
[syslog.txt](https://github.com/ubports/ubuntu-touch-for-oneplus-one/files/162214/syslog.txt)

**Comment by UniversalSuperBox** [comment]
Cleaning up old issues
