### ISSUE TITLE
can't change root password

### ISSUE THREAD

**Issue by bronch** [ubports/ubuntu-touch-for-oneplus-one#38]
I don't know the root password, I tried with `phablet`, `ubuntu` and my passphrase, but it doesn't work, so what's the default password? (installed via MultiROM, don't know if it could help)

**Comment by peat-psuwit** [comment]
On Ubuntu, root password is intentionally disabled. You'll have to use sudo to perform root operation. In Ubuntu touch case, the password is your lock screen password, and, unlike normal Ubuntu, you can't set root password without making device R/W (which is not recommended). FYI, the username of normal user in Ubuntu touch is "phablet"

**Comment by UniversalSuperBox** [comment]
Closed due to inactivity. Please report all new bugs at Launchpad. See https://github.com/ubports/ubuntu-touch-for-oneplus-one/issues/36 for more.
