### ISSUE TITLE
Development is dead?

### ISSUE THREAD

**Issue by cojack** [ubports/ubuntu-touch-for-oneplus-one#40]
Any information?

**Comment by mariogrip** [comment]
Nope, we are more live than ever. but we don't use this repo anymore.

**Comment by verymilan** [comment]
You told this to me also a few months ago but there is still no Bluetoosh, no Camera, no Headphones and Videodecoding is still not marked as tested.
Something new on the Port i should know? :/

**Comment by ubports-gerrit** [comment]
we have been busy updating the android core to 5.1, + we have lots of
devices to maintain + I do this at my free time, it's not that easy :)

2016-06-18 20:05 GMT+02:00 tchncs notifications@github.com:

**Comment by mariogrip** [comment]
Btw, that was me, used the wrong github account. @ubports-gerrit is a bot account

**Comment by cojack** [comment]
@mariogrip could you provide an link to up-to date repo?
