### ISSUE TITLE
mkbootimg fix

### ISSUE THREAD

**Issue by robbyf** [ubports/ubuntu-touch-for-oneplus-one#5]
Here is the updated file so you don't need to manually move the binary each build.

Add this file https://github.com/CyanogenMod/android_system_core/blob/252000b6495dcf2d5a879e3824fb6127df692e52/mkbootimg/unpackbootimg.c

and edit Android.mk 

here is the updated 
https://github.com/CyanogenMod/android_system_core/blob/cm-12.0/mkbootimg/Android.mk

edit: working for me with these fixes, may lead to other unresolved errors

**Comment by robbyf** [comment]
ok easier way..ignore the above



/system/core/mkbootimg/Android.mk comment out LOCAL_CLFAGS := Werror

tested and built

**Comment by mariogrip** [comment]
Fixed in 5.1
