### ISSUE TITLE
build fail when create a recovery.img

### ISSUE THREAD

**Issue by lozo2010** [ubports/ubuntu-touch-for-oneplus-one#9]
This error:  make: *** [/home/lozo/ubu/out/target/product/bacon/recovery.img] Error 1

**Comment by mariogrip** [comment]
Can you provide some more of the error?

**Comment by lozo2010** [comment]
/home/lozo/ubu/out/host/linux-x86/bin/minigzip < /home/lozo/ubu/out/target/product/bacon/ramdisk-recovery.cpio > /home/lozo/ubu/out/target/product/bacon/ramdisk-recovery.img
----- Making recovery image ------
usage: mkbootimg
       --kernel <filename>
       --ramdisk <filename>
       [ --second <2ndbootloader-filename> ]
       [ --cmdline <kernel-commandline> ]
       [ --board <boardname> ]
       [ --base <address> ]
       [ --pagesize <pagesize> ]
       -o|--output <filename>
make: *** [/home/lozo/ubu/out/target/product/bacon/recovery.img] Error 1

**Comment by lozo2010** [comment]
Generating master DTB... completed
Made DT image: /home/lozo/ubu/out/target/product/bacon/dt.img
Target Ubuntu Touch ram disk: /home/lozo/ubu/out/target/product/bacon/ramdisk.img
Downloading ubuntu-touch-generic-initrd version 0.83
12212 blocks
----- Making recovery image ------
Copying baseline ramdisk...
Modifying ramdisk contents...
cp: cannot stat ‘/home/lozo/ubu/out/target/product/bacon/root/init.recovery.*.rc’: No such file or directory
make: [/home/lozo/ubu/out/target/product/bacon/recovery/root.ts] Error 1 (ignored)
mkdir -p /home/lozo/ubu/out/target/product/bacon/recovery/root/system/bin
Modifying default.prop
sed -i 's/ro.build.date.utc=.*/ro.build.date.utc=0/g' /home/lozo/ubu/out/target/product/bacon/recovery/root/default.prop
sed -i 's/ro.adb.secure=1//g' /home/lozo/ubu/out/target/product/bacon/recovery/root/default.prop
----- Made recovery filesystem --------/home/lozo/ubu/out/target/product/bacon/recovery/root
----- Making uncompressed recovery ramdisk ------
/home/lozo/ubu/out/host/linux-x86/bin/mkbootfs /home/lozo/ubu/out/target/product/bacon/recovery/root > /home/lozo/ubu/out/target/product/bacon/ramdisk-recovery.cpio
----- Making recovery ramdisk ------
/home/lozo/ubu/out/host/linux-x86/bin/minigzip < /home/lozo/ubu/out/target/product/bacon/ramdisk-recovery.cpio > /home/lozo/ubu/out/target/product/bacon/ramdisk-recovery.img
----- Making recovery image ------
usage: mkbootimg
       --kernel <filename>
       --ramdisk <filename>
       [ --second <2ndbootloader-filename> ]
       [ --cmdline <kernel-commandline> ]
       [ --board <boardname> ]
       [ --base <address> ]
       [ --pagesize <pagesize> ]
       -o|--output <filename>
make: *** [/home/lozo/ubu/out/target/product/bacon/recovery.img] Error 1

**Comment by mariogrip** [comment]
look here: https://github.com/ubuntu-touch-oneplus-one/ubuntu-touch-for-oneplus-one/issues/5

Or

Replace mkbootimg with this https://github.com/ubuntu-touch-oneplus-one/ubuntu-touch-for-oneplus-one/blob/master/tools/mkbootimg?raw=true

**Comment by robbyf** [comment]
https://github.com/ubuntu-touch-oneplus-one/ubuntu-touch-for-oneplus-one/issues/6

my fix should work with this issue as well.

**Comment by lozo2010** [comment]
I dont fix the error...

**Comment by wdehoog** [comment]
Got the same problem. Replacing mkbootimg with the above mentioned one (from github) fixed it.
